version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: terraform-validate
          command: |
            git clone https://github.com/tfutils/tfenv.git ~/.tfenv
            export PATH="$HOME/.tfenv/bin:$PATH"
            export TF_CURL_OUTPUT=1
            tfenv install
            terraform validate

orbs:
  aws-cli: circleci/aws-cli@1.0.0
