version: 2.1
jobs:
  run_pre-commit-terraform_hooks:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: configure_terraform_env
          command: |
            set -x
            git clone https://github.com/tfutils/tfenv.git ~/.tfenv
            export PATH="$HOME/.tfenv/bin:$PATH"
            export TF_CURL_OUTPUT=1
            if ls -a | grep .tf | grep -w "required_version" *.tf; then
              echo "Found required_version declaration, using min-required"
              tfenv install min-required
            else
              echo "No required_version declaration, using latest"
              tfenv install latest
            fi
            tfenv use
            terraform version
      - run:
          name: setup_pre-commit
          command: |
            set -x
            sudo apt-get install software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get update -y
            sudo apt-get install python3.7 python3-pip -y
            pip3 install pre-commit
            pre-commit --version
            if ls -a | grep .pre-commit-config.yaml; then
              echo "Found .pre-commit-config.yaml!"
              pre-commit install
            else
              echo "No .pre-commit-config.yaml found, exiting"
              return 1
            fi
      - run:
          name: pre-commit_run
          command: pre-commit run --all-files

workflows:
  version: 2
  test_my_terraform_module:
    jobs:
      - run_pre-commit-terraform_hooks


orbs:
  aws-cli: circleci/aws-cli@1.0.0
